// apps/vue/src/app/app.component.vue
<script setup lang="ts">
import { HelloWorldComponent } from "./hello-world";
</script>

<template>
  <div>
    <sui-button
      aria-label="Button aria label."
      @click="() => console.debug('click')"
    >
      Stencil button
    </sui-button>
    <sui-input
      aria-label="Input aria label."
      placeholder="Lorem ipsum"
      @input="(event: InputEvent) => console.debug((event.target as HTMLInputElement).value)"
    />
  </div>

  <div>
    <a
      href="https://vitejs.dev"
      target="_blank"
    >
      <img
        src="/vite.svg"
        class="logo"
        alt="Vite logo"
      />
    </a>
    <a
      href="https://vuejs.org/"
      target="_blank"
    >
      <img
        src="./assets/vue.svg"
        class="logo vue"
        alt="Vue logo"
      />
    </a>
  </div>
  <HelloWorldComponent msg="Vite + Vue" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// apps/react/src/app/app.component.tsx
import { useState } from "react";

import reactLogo from "./assets/react.svg";

import viteLogo from "/vite.svg";

import "./app.module.css";

export const AppComponent: React.FC = () => {
  const [count, setCount] = useState(0);

  return (
    <>
      <div>
        <sui-button
          aria-label="Button aria label."
          onClick={() => console.debug("click")}
        >
          Stencil button
        </sui-button>
        <sui-input
          aria-label="Input aria label."
          placeholder="Lorem ipsum"
          onInput={(event: InputEvent) => console.debug((event.target as HTMLInputElement).value)}
        />
      </div>
      <div>
        <a
          href="https://vitejs.dev"
          target="_blank"
          rel="noreferrer"
        >
          <img
            src={viteLogo}
            className="logo"
            alt="Vite logo"
          />
        </a>
        <a
          href="https://react.dev"
          target="_blank"
          rel="noreferrer"
        >
          <img
            src={reactLogo}
            className="logo react"
            alt="React logo"
          />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>count is {count}</button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">Click on the Vite and React logos to learn more</p>
    </>
  );
};
